### ISSUE TITLE
Notifications model

### ISSUE THREAD

**Issue by khamza85** [exadelsandbox2022feb/main#23]
Within Domain project, create notifications models. It might be needed if notifications should be sent asynchronously.

**Comment by Anvarxon** [comment]
@khamza85 What type of attributes, properties and notification models you would recommended to include?

**Comment by khamza85** [comment]
@Anvarxon , according to the specification, we have
- Send a booking summary to email
- Notify about auto cancellation (upon user vacation/employment termination)

Notification should 
- Reference to booking #22 
- From the above reference we can navigate to who, when, and where is booking i.e. the summary details
- In case we need to queue up notifications in a database, we can add fields like SentDate.
