### ISSUE TITLE
First commit Vasili

### ISSUE THREAD

**Issue by khamza85** [exadelsandbox2022feb/main#5]
Create a file under /tmp folder using your github username as a file name. The file should contain one line text with your email.

**Comment by Bazilis** [comment]
Add pull request

**Comment by khamza85** [comment]
> Add pull request

Nice 👍 

1. Please link PR to this issue. Then once PR is approved, this issue should automatically progress to Done :)
2. You need the approval of 3 people. I approved, so 2 more people
