### ISSUE TITLE
Step “Select a booking type” (4th) | Steps on Telegram

### ISSUE THREAD

**Issue by Anvarxon** [exadelsandbox2022feb/main#93]
**1. Throw to user in form of buttons three available periods after the text “Select booking type:”**

- One day
- Continuous
- Recurring

**2. If one day period is chosen:**
- Send to a user the text “Select booking date”. User can select only one date for booking. At first throw three upcoming months (as buttons), when month is selected, throw available dates for booking (as buttons)

**3. If continuous period is chosen:**
- Send to a user the text “Select booking first and last day ”. At first throw three upcoming months (as buttons), when month is selected, throw available dates for booking (as buttons) twice. Which means, every single day between selected ones are going to be booked;

**4. If recurring period is chosen:**
- Send to a user the text “Define recurring parameters ”. Anvar, need to check BA’s docs for details. Probably, user should select several dates on calendar or by buttons

**5. After selecting a date type, proceed to the step for parking.**

**Comment by Andrei-Ha** [comment]
implemented
