### ISSUE TITLE
Step "Specify workplace parameters" (6th) | Steps on Telegram

### ISSUE THREAD

**Issue by Anvarxon** [exadelsandbox2022feb/main#95]
**1. Throw two buttons “YES” and “NO” (Names are specified further)**
- If “YES” is chosen, send to the empty step of configuring specifications (needs more steps to be developed). [Name of the button: “Yes, I have special preferences”]

- If “NO”, save the entry to cache/database, and send user to step “Review booking” [Name of the button: “No, I can take any available workplace”]

**Comment by Andrei-Ha** [comment]
implemented
